# Generated by Django 4.0.4 on 2022-05-07 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='spouse_name',
        ),
        migrations.RemoveField(
            model_name='historicalcustomuser',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='historicalcustomuser',
            name='spouse_name',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='historicalcustomuser',
            name='email',
            field=models.EmailField(db_index=True, max_length=255, verbose_name='Correo electrónico'),
        ),
    ]
