# Generated by Django 4.0.4 on 2022-05-10 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='status',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=40, unique=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='historicalcustomuser',
            name='email',
            field=models.EmailField(db_index=True, max_length=40, verbose_name='Correo electrónico'),
        ),
    ]
