# Generated by Django 4.0.4 on 2022-05-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_historicaluser_email_remove_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='email',
            field=models.EmailField(db_index=True, max_length=20, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=20, null=True, unique=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Nombres'),
        ),
    ]
